# Generated by Django 5.1.3 on 2024-12-12 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_userattempt_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
    ]
