# Generated by Django 5.1.3 on 2024-12-14 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_group_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='group_name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
