# Generated by Django 5.1.3 on 2024-12-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_faculty_name_remove_specialty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=255, verbose_name='faculty'),
        ),
    ]
